/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package trees

import bstrees.implementations.AVLTree
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class AVLTreeTest {
    private lateinit var avlTree: AVLTree<Int, Int>

    @BeforeEach
    fun setup() {
        avlTree = AVLTree<Int, Int>()
    }

    @Test
    fun `simple array test`() {
        val array = intArrayOf(1, 2, 3, 4, 5)
        for (i in array) {
            avlTree.set(i, -i)
        }
        val expectedGet = -5
        val actualGet = avlTree.get(5)
        assertEquals(expectedGet, actualGet, "Get method must return associated with key value")
        val expectedSize = 5
        val actualSize = avlTree.size
        assertEquals(expectedSize, actualSize, "Size of avl tree must correspond to number key-value pairs")
    }

    @Test
    fun `size of avl tree with duplicate keys`() {
        for (i in 1..10) {
            avlTree.set(i, 30 + i)
        }
        for (i in 6..10) {
            avlTree.set(i, 0)
        }

        val expectedSize = 10
        val actualSize = avlTree.size
        assertEquals(
            expectedSize, actualSize,
            "Size of avl tree must not change with overwriting an existing key"
        )
    }

    @Test
    fun `set keys twice`() {
        for (i in 1..10) {
            avlTree.set(i, 30 + i)
        }
        for (i in 1..10) {
            avlTree.set(i, 0)
        }

        val expectedSize = 10
        val actualSize = avlTree.size
        assertEquals(
            expectedSize, actualSize,
            "Size of avl tree must not change with overwriting an existing key"
        )
    }


}
