/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package trees

import bstrees.implementations.AVLTree
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals

class AVLTreeTest {
    private lateinit var avlTree: AVLTree<Int, Int>

    @BeforeEach
    fun setup() {
        avlTree = AVLTree<Int, Int>()
    }

    @Test
    fun `simple array test`() {
        val array = intArrayOf(0, 1, 2, 3, 4)
        for (i in array) {
            avlTree.set(i, -i)
        }
        val expectedGet: Array<Int?> = Array(5, { i -> -i })
        val actualGet: Array<Int?> = Array(5, { i -> avlTree.get(i) })
        assertContentEquals(expectedGet, actualGet, "Get method must return the value associated with the key")
        val expectedSize = 5
        val actualSize = avlTree.size
        assertEquals(expectedSize, actualSize, "Size the tree must correspond to the number key-value pairs")
    }

    @Test
    fun `size of avl tree with duplicate keys`() {
        for (i in 1..10) {
            avlTree.set(i, 30 + i)
        }
        for (i in 6..10) {
            avlTree.set(i, 0)
        }

        val expectedSize = 10
        val actualSize = avlTree.size
        assertEquals(
            expectedSize, actualSize,
            "Size of the tree must not change after overwriting an existing key"
        )
    }

    @Test
    fun `set keys twice`() {
        for (i in 1..10) {
            avlTree.set(i, 30 + i)
        }
        for (i in 1..10) {
            avlTree.set(i, 0)
        }

        val expectedSize = 10
        val actualSize = avlTree.size
        assertEquals(
            expectedSize, actualSize,
            "Size of the tree must not change after overwriting an existing key"
        )
    }

    @Test
    fun `simple remove`() {
        avlTree[0] = 5

        val expectedResult = 5
        val actualResult = avlTree.remove(0)
        val expectedSize = 0
        val actualSize = avlTree.size

        assertEquals(
            expectedResult, actualResult,
            "Remove must return removed value"
        )
        assertEquals(
            expectedSize, actualSize,
            "Size tree must decrease after removing the existing key"
        )
    }

    @Test
    fun `remove a non-existent key`() {
        avlTree[0] = 15
        avlTree.remove(0)

        val expectedResult = null
        val actualResult = avlTree.remove(0)
        assertEquals(
            expectedResult, actualResult,
            "Remove a non-existent key must return null"
        )
    }

    @Test
    fun `simple iterator test`() {
        val keys = intArrayOf(1, 7, 4, 9, 2, -44, 3)
        val values = intArrayOf(19, 14, 31, 17, 12, -34, 0)
        for (i in 0..<keys.size) {
            avlTree[keys[i]] = values[i]
        }

        val expectedResult: Array<Int?> = arrayOf(-34, 19, 12, 0, 31, 14, 17)
        val iterator = avlTree.iterator()
        val actualResult: Array<Int?> = Array(7, { i -> iterator.next().second })
        assertContentEquals(expectedResult, actualResult, "Iterator must return vertices in keys order")

    }
}
