/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package treesTests

import bstrees.implementations.AVLTree
import org.junit.jupiter.api.BeforeEach
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class AVLTreeTest {
    private lateinit var avlTree: AVLTree

    @BeforeEach
    fun setup() {
        avlTree = AVLTree()
    }

    /*    @Test
        fun someAVLTreeMethodTest() {

            val expectedResult =
            val actualResult =
            assertEquals(expectedResult, actualResult, "Assert text")
        }*/
}
