name: Build & Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: '17'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Test
        run: gradle build
