name: CI_Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  CI_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Check code cleanliness
        run: ./gradlew clean build
        continue-on-error: true

      - name: Run tests
        run: ./gradlew test
